language: php

matrix:
    include:
        - php: 7.2
          env: deps=low
        - php: 7.3
        - php: 7.4
    fast_finish: true

before_script:
  - phpenv config-rm xdebug.ini || echo 'XDebug not enabled'
  - if [[ $deps = low ]]; then make update-min; else make install; fi

script:
  - if [[ $deps = low ]]; then make test-min; else make test; fi
